# Site settings
theme:          jekyll-theme-cayman
title:          Dattatreya Tripathy
description:    Associate Software Engineer at ServiceNow
baseurl:        ""
url:            "https://dt97.github.io"

# Author settings
author:
  name:         Dattatreya Tripathy
  url:          https://dt97.github.io
  email:        dt.kanha@gmail.com
